# -*- coding: utf-8 -*-
import io, json, os
from collections import OrderedDict

BASE = r"C:\Projek Coding\Sistem Kewangan Masjid\sppkms-v2"

NEW = {
    '"Padam" hanya menetapkan status TIDAK AKTIF — rekod bank tidak dibuang kerana mungkin dirujuk transaksi lama.': '"Delete" only sets the status to INACTIVE — the bank record is not removed as it may be referenced by past transactions.',
    "% Padanan": "% Match",
    "(BELUM DISET — sila isi TELEGRAM_WEBHOOK_SECRET dalam .env)": "(NOT SET — please fill in TELEGRAM_WEBHOOK_SECRET in .env)",
    "(Dr Bank/Aset, Cr 100-10000 Dana Terkumpul) telah dijana.": "(Dr Bank/Assets, Cr 100-10000 Accumulated Fund) has been generated.",
    "(akan dipindah ke 100-10000 DANA TERKUMPUL)": "(to be transferred to 100-10000 ACCUMULATED FUND)",
    "(jurnal": "(journal",
    "(kosongkan untuk kekal)": "(leave blank to keep)",
    "(lalai)": "(default)",
    "(permulaan rantai)": "(start of chain)",
    "(semak=off) — kaunter auto SPPKMS lama TIDAK diganggu. Bayaran jenis": "(semak=off) — the old SPPKMS auto counter is NOT affected. Payments of type",
    "(tiada)": "(none)",
    "-- Pilih Kategori --": "-- Select Category --",
    "0 = maker-checker dimatikan.": "0 = maker-checker disabled.",
    "0 = notifikasi dimatikan.": "0 = notifications disabled.",
    "10 Security Event Terkini": "10 Latest Security Events",
    "20 Aktiviti Audit Terkini": "20 Latest Audit Activities",
    "20 rekod terakhir. Checksum SHA-256 disimpan bagi setiap fail untuk uji pulih.": "Last 20 records. A SHA-256 checksum is stored for every file for restore testing.",
    "50 terkini": "50 latest",
    "AI hanya mencipta": "AI only creates",
    "AKTIF": "ACTIVE",
    "AMARAN DEFISIT:": "DEFICIT WARNING:",
    "AMARAN KUAT:": "STRONG WARNING:",
    "Abai": "Ignore",
    "Abaikan baris penyata ini?": "Ignore this statement line?",
    "Admin sentiasa lepas terus.": "Admin always passes through.",
    "Akaun / SNT": "Account / Accum. Depn",
    "Akaun Belanja": "Expense Account",
    "Akaun Sementara": "Suspense Account",
    "Akaun Sementara 300-99990: baki": "Suspense Account 300-99990: balance",
    "Akaun Tabung Baharu (COA 300-04xxx)": "New Fund Account (COA 300-04xxx)",
    "Akses baca sahaja — pengesahan oleh admin/bendahari.": "Read-only access — confirmation by admin/treasurer.",
    "Aktif (boleh log masuk)": "Active (can log in)",
    "Aktif (dipaparkan pada penyata)": "Active (shown on statements)",
    "Aktifkan": "Activate",
    "Aktifkan backup automatik": "Enable automatic backup",
    "Amaran": "Alert",
    "Amaran belanjawan pada borang Perbelanjaan (semakan peruntukan masa nyata)": "Budget warning on the Expenditure form (real-time allocation check)",
    "Amaran defisit dana/tabung harian (SecurityEvent HIGH + Telegram, sekali sehari)": "Daily fund/trust deficit alert (HIGH SecurityEvent + Telegram, once a day)",
    "Ambang Notifikasi Baki Bank Rendah (RM)": "Low Bank Balance Notification Threshold (RM)",
    "Anda mempunyai akses baca sahaja.": "You have read-only access.",
    "Apabila DIHIDUPKAN, setiap": "When ENABLED, every",
    "Aset Tetap": "Fixed Assets",
    "BAYARAN (Belanja)": "PAYMENT (Expense)",
    "BELANJA": "EXPENSES",
    "BELUM": "PENDING",
    "BERJAYA": "SUCCESS",
    "Backup APP_KEY secara BERASINGAN": "Back up the APP_KEY SEPARATELY",
    "Backup Luar Tapak (Google Drive)": "Offsite Backup (Google Drive)",
    "Backup Sekarang": "Backup Now",
    "Backup Terakhir": "Last Backup",
    "Bahasa": "Language",
    "Baki Awal": "Opening Balance",
    "Baki Bulanan": "Monthly Balances",
    "Baki dikira terus daripada jurnal (POSTED) sehingga akhir setiap bulan.": "Balances are computed directly from POSTED journals up to the end of each month.",
    "Baki rendah:": "Low balance:",
    "Bandar": "City",
    "Baris DIPADAN terkini": "Recently MATCHED lines",
    "Baris Penyata": "Statement Lines",
    "Baris Penyata BELUM DIPADAN": "UNMATCHED Statement Lines",
    "Baris pengimbang ke": "The balancing line to",
    "Base URL (pilihan)": "Base URL (optional)",
    "Baucer Bayaran (PV)": "Payment Voucher (PV)",
    "Baucer PWR": "Petty Cash Voucher",
    "Bayaran/rekupmen oleh": "Payments/top-ups by the",
    "Belum Dimuktamadkan": "Not Finalised",
    "Belum ada backup dijalankan.": "No backups have been run yet.",
    "Belum ada padanan.": "No matches yet.",
    "Belum dikonfigurasi — muat naik fail JSON kunci service account.": "Not configured — upload the service account key JSON file.",
    "Belum selesai": "Unresolved",
    "Benarkan baki defisit (tiada amaran merah)": "Allow deficit balance (no red warning)",
    "Bersih Penyata lwn Buku (RM)": "Net Statement vs Book (RM)",
    "Beza (RM)": "Difference (RM)",
    "Bilangan Digit (2-8)": "Number of Digits (2-8)",
    "Bot Telegram (Group Resit)": "Telegram Bot (Receipt Group)",
    "Buang penapis:": "Remove filter:",
    "Butiran Draf (boleh diubah sebelum pengesahan)": "Draft Details (editable before confirmation)",
    "Butiran Permohonan": "Request Details",
    "Cari Voucher": "Find Voucher",
    "Cari ref voucher / deskripsi / amaun...": "Search voucher ref / description / amount...",
    "Cari resit, baucer, nama, deskripsi, aset...": "Search receipts, vouchers, names, descriptions, assets...",
    "Carian Global": "Global Search",
    "Carian fuzzy terhadap nama kod akaun (COA) dan label tempatan masjid — hanya padanan ≥ 40% dipaparkan.": "Fuzzy search against chart of accounts (COA) names and mosque local labels — only matches ≥ 40% are shown.",
    "Chat ID Group": "Group Chat ID",
    "Checker": "Checker",
    "Cipta Klien & Jana Kredensial": "Create Client & Generate Credentials",
    "Cipta Klien API Baharu": "Create New API Client",
    "Cr Bank": "Cr Bank",
    "Cr akaun aset (kos penuh). Status aset menjadi DILUPUSKAN.": "Cr asset account (full cost). The asset status becomes DISPOSED.",
    "Cuba Semula": "Retry",
    "Cubaan": "Attempts",
    "DIHANTAR": "SENT",
    "DIKUNCI —": "are LOCKED —",
    "DIMATIKAN (0)": "DISABLED (0)",
    "Daerah": "District",
    "Daerah / Negeri": "District / State",
    "Daftar Akaun Bank": "Register Bank Accounts",
    "Daftar dengan:": "Register with:",
    "Dana": "Fund",
    "Dapatkan token:": "Get a token:",
    "Dari": "From",
    "Data": "Data",
    "Debit": "Debit",
    "Defisit?": "Deficit?",
    "Deskripsi Penyata": "Statement Description",
    "Dialect API": "API Dialect",
    "Dibenarkan": "Allowed",
    "Digunakan": "In use",
    "Digunakan dalam borang": "Used in forms",
    "Dihantar oleh": "Sent by",
    "Dipadan / Belum": "Matched / Unmatched",
    "Diputuskan": "Decided",
    "Disclaimer": "Disclaimer",
    "Disimpan tersulit dalam vault": "Stored encrypted in the vault",
    "Dokumen Asal (Telegram)": "Original Document (Telegram)",
    "Dokumentasi pembangun luar:": "External developer documentation:",
    "Dr Bank": "Dr Bank",
    "Draf": "Draft",
    "Draf AI": "AI Draft",
    "Draf AI Menunggu": "AI Drafts Pending",
    "Draf Menunggu Pengesahan": "Drafts Awaiting Confirmation",
    "Draf di bawah dicipta oleh AI daripada resit yang dihantar ke group Telegram.": "The drafts below were created by AI from receipts sent to the Telegram group.",
    "Dual-Write SPPKMS (Sistem Lama)": "SPPKMS Dual-Write (Legacy System)",
    "Dump DB harian (02:00)": "Daily DB dump (02:00)",
    "Edit Bank — Slot": "Edit Bank — Slot",
    "Edit Info Masjid (Admin)": "Edit Mosque Info (Admin)",
    "Edit Pemetaan Kod": "Edit Code Mapping",
    "Edit Pengguna": "Edit User",
    "Edit Tandatangan Penyata": "Edit Statement Signature",
    "Emel": "Email",
    "Entiti": "Entity",
    "Event": "Event",
    "Fail": "File",
    "Fail Service Account JSON": "Service Account JSON File",
    "Fail service account TELAH dikonfigurasi (muat naik semula untuk ganti).": "Service account file HAS been configured (re-upload to replace).",
    "Fax": "Fax",
    "Font besar": "Large font",
    "Font biasa": "Normal font",
    "Font kecil": "Small font",
    "GAGAL": "FAILED",
    "Garis lurus:": "Straight line:",
    "HASIL": "REVENUE",
    "HIDUP": "ON",
    "Had Kadar (panggilan/minit)": "Rate Limit (calls/minute)",
    "Had Kelulusan Maker-Checker (RM)": "Maker-Checker Approval Threshold (RM)",
    "Had kelulusan semasa:": "Current approval threshold:",
    "Had/min": "Limit/min",
    "Halaman ini akan tersedia pada fasa pembinaan berikutnya.": "This page will be available in the next build phase.",
    "Hantar Semua Tertunggak": "Send All Pending",
    "Hidupkan": "Enable",
    "Hingga": "To",
    "Hubungi Kami": "Contact Us",
    "ID": "ID",
    "ID Folder Google Drive": "Google Drive Folder ID",
    "IP": "IP",
    "IP Allowlist": "IP Allowlist",
    "IP Allowlist (opsional, pisah koma)": "IP Allowlist (optional, comma-separated)",
    "Import & Padan Auto": "Import & Auto Match",
    "Istilah Tempatan": "Local Term",
    "JUMLAH BELANJA": "TOTAL EXPENSES",
    "JUMLAH HASIL": "TOTAL REVENUE",
    "Jadikan Default": "Make Default",
    "Jadual susut nilai:": "Depreciation schedule:",
    "Jalankan pengesahan hash-chain ke atas keseluruhan jejak audit?": "Run hash-chain verification on the entire audit trail?",
    "Jana & Pos Bulan Ini": "Generate & Post This Month",
    "Jana & pos jurnal susut nilai bulan ini untuk semua aset aktif? Aset yang sudah diposkan bulan ini akan dilangkau (idempoten).": "Generate & post this month's depreciation journal for all active assets? Assets already posted this month will be skipped (idempotent).",
    "Jawatan": "Position",
    "Jejak Audit (hash-chain, append-only)": "Audit Trail (hash-chain, append-only)",
    "Jejak Penuh": "Full Trail",
    "Jelaskan (reclass) suspense dahulu": "Clear (reclass) the suspense first",
    "Jenis Guna": "Usage Type",
    "Jenis Lalai Draf": "Default Draft Type",
    "Jenis dokumen:": "Document type:",
    "Jika mana-mana akaun bank jatuh bawah ambang ini: notifikasi loceng + amaran": "If any bank account falls below this threshold: bell notification + daily",
    "Jurnal": "Journal",
    "Jurnal (JNL)": "Journal (JNL)",
    "Jurnal pelupusan: Dr SNT (susut terkumpul) + Dr 600-99990 (baki nilai buku) /": "Disposal journal: Dr accumulated depreciation + Dr 600-99990 (remaining book value) /",
    "Jurnal: Dr 650-10000 / Cr akaun SNT aset. Berhenti automatik apabila susut terkumpul = kos.": "Journal: Dr 650-10000 / Cr asset accumulated depreciation account. Stops automatically when accumulated depreciation = cost.",
    "KUTIPAN (Terimaan)": "COLLECTION (Receipt)",
    "Kadar": "Rate",
    "Kapsyen:": "Caption:",
    "Kata Laluan": "Password",
    "Kata Laluan (min 6)": "Password (min 6)",
    "Kata Laluan Baharu (min 6 aksara)": "New Password (min 6 characters)",
    "Kata Laluan Semasa": "Current Password",
    "Kata laluan TELAH dikonfigurasi (isi semula untuk ganti).": "Password HAS been configured (re-enter to replace).",
    "Kata laluan baharu (min 6 aksara)": "New password (min 6 characters)",
    "Kata laluan baharu berkuat kuasa pada log masuk seterusnya selepas anda log keluar.": "The new password takes effect on your next login after you log out.",
    "Kawalan Dalaman": "Internal Controls",
    "Kawalan ini menyokong pengasingan tugas (segregation of duties): pembuat (maker) dan": "These controls support segregation of duties: the maker and",
    "Kedua-dua": "Both",
    "Keluar/Dr (RM)": "Out/Dr (RM)",
    "Kelulusan Maker-Checker": "Maker-Checker Approvals",
    "Kemajuan Setup": "Setup Progress",
    "Kemaskini Info Masjid": "Update Mosque Info",
    "Kemaskini Kata Laluan": "Update Password",
    "Kemaskini Maklumat Bank": "Update Bank Details",
    "Kemaskini Pemetaan": "Update Mapping",
    "Kemaskini Pengguna": "Update User",
    "Kemaskini Tandatangan": "Update Signature",
    "Kembali": "Back",
    "Kembali ke Tetapan API": "Back to API Settings",
    "Keputusan Padanan untuk": "Match Results for",
    "Keputusan untuk": "Results for",
    "Keselamatan 7 Hari": "Security 7 Days",
    "Keyakinan AI": "AI Confidence",
    "Keyakinan AI hanya": "AI confidence is only",
    "Keyakinan AI:": "AI Confidence:",
    "Klien": "Client",
    "Klien API Berdaftar": "Registered API Clients",
    "Kod / Nama Aset": "Asset Code / Name",
    "Kod Akaun": "Account Code",
    "Kod Akaun (200 Aset Tetap / 250 Aset Semasa / 300 Liabiliti)": "Account Code (200 Fixed Assets / 250 Current Assets / 300 Liabilities)",
    "Konfigurasi Backup": "Backup Configuration",
    "Kongsikan folder kepada e-mel service account terlebih dahulu.": "Share the folder with the service account email first.",
    "Kredensial Klien Baharu — SALIN SEKARANG (ditunjuk SEKALI sahaja)": "New Client Credentials — COPY NOW (shown only ONCE)",
    "Kredensial SPPKMS Lama": "Legacy SPPKMS Credentials",
    "Kredit": "Credit",
    "Kunci API": "API Key",
    "Kunci API & token bot": "API keys & bot tokens are",
    "Kutipan": "Collections",
    "LEBIHAN / (KURANGAN)": "SURPLUS / (DEFICIT)",
    "Label Tempatan": "Local Label",
    "Lajur: tarikh (Y-m-d atau d/m/Y), deskripsi, debit, kredit, baki — baris pertama header.": "Columns: date (Y-m-d or d/m/Y), description, debit, credit, balance — first row is the header.",
    "Laman Web": "Website",
    "Langganan Webhook (peristiwa keluar)": "Webhook Subscriptions (outgoing events)",
    "Latensi (ms)": "Latency (ms)",
    "Lengkapkan langkah berikut mengikut urutan untuk pemasangan baharu.": "Complete the following steps in order for a fresh installation.",
    "Lihat JSON mentah AI": "View raw AI JSON",
    "Log API": "API Log",
    "Log Masuk": "Log In",
    "Log Masuk Terakhir": "Last Login",
    "Log Panggilan API": "API Call Log",
    "Log Panggilan API — 100 Terakhir": "API Call Log — Last 100",
    "Log Ralat Aplikasi": "Application Error Log",
    "Log audit & keselamatan (setiap jam)": "Audit & security logs (hourly)",
    "Login": "Login",
    "Login Gagal 24 Jam": "Failed Logins 24 Hours",
    "Logo Masjid (untuk resit & penyata)": "Mosque Logo (for receipts & statements)",
    "Logo dipaparkan pada resit dan penyata kewangan.": "The logo is shown on receipts and financial statements.",
    "Lulus": "Approve",
    "Lulus & rekodkan pembayaran": "Approve & record payment",
    "Lupus": "Dispose",
    "MATI": "OFF",
    "MELEBIHI PERUNTUKAN": "OVER ALLOCATION",
    "Maklumat Ekstrakan AI": "AI Extraction Details",
    "Masa": "Time",
    "Masuk/Cr (RM)": "In/Cr (RM)",
    "Masukkan baki awal tahun (bank/aset/liabiliti) dan muktamadkan.": "Enter the opening balances for the year (bank/assets/liabilities) and finalise.",
    "Masukkan sekurang-kurangnya 2 aksara untuk mencari.": "Enter at least 2 characters to search.",
    "Matikan": "Disable",
    "Mesej": "Message",
    "Mod Backup": "Backup Mode",
    "Mod gelap / cerah": "Dark / light mode",
    "Mod semasa:": "Current mode:",
    "Modul": "Module",
    "Muat Naik": "Upload",
    "Muat Naik Logo (PNG/JPG, maks 2MB)": "Upload Logo (PNG/JPG, max 2MB)",
    "Muat Naik Logo Masjid": "Upload Mosque Logo",
    "Muat Naik Penyata Bank (CSV)": "Upload Bank Statement (CSV)",
    "Muktamad & Kunci": "Finalise & Lock",
    "Muktamad & Kunci baki awal": "Finalise & Lock opening balances for",
    "Mulakan backup penuh DB sekarang?": "Start a full DB backup now?",
    "Nama Bank": "Bank Name",
    "Nama Dana": "Fund Name",
    "Nama Klien": "Client Name",
    "Nama Log Masuk": "Login Name",
    "Nama Masjid": "Mosque Name",
    "Nama Penuh": "Full Name",
    "Negeri": "State",
    "Nilai Buku (RM)": "Book Value (RM)",
    "No Akaun": "Account No",
    "No Rujukan / Resit": "Reference / Receipt No",
    "No resit/baucer dihantar sebagai": "Receipt/voucher numbers are sent as",
    "Nombor Mula": "Starting Number",
    "Nombor seterusnya:": "Next number:",
    "Notifikasi": "Notifications",
    "Notifikasi Terkini": "Latest Notifications",
    "Nyahaktif": "Deactivate",
    "Nyahaktifkan": "Deactivate",
    "Nyahaktifkan bank slot": "Deactivate bank slot",
    "Output Pengesahan Rantai (sppkms:verify-audit-chain)": "Chain Verification Output (sppkms:verify-audit-chain)",
    "Padam langganan webhook": "Delete webhook subscription",
    "Padam pemetaan": "Delete mapping",
    "Padam tandatangan": "Delete signature",
    "Padan": "Match",
    "Padanan Manual": "Manual Match",
    "Padanan Manual — Baris Penyata": "Manual Match — Statement Line",
    "Papar Laporan": "Show Report",
    "Pelupusan Aset:": "Asset Disposal:",
    "Pembayaran": "Payments",
    "Pemberi": "Donor",
    "Pemetaan Label Tempatan → Kod Akaun (COA)": "Local Label → Account Code (COA) Mapping",
    "Pemohon (Maker)": "Requester (Maker)",
    "Pendaftaran Webhook Telegram": "Telegram Webhook Registration",
    "Penerima / Pemberi": "Payee / Donor",
    "Penerimaan": "Receipts",
    "Pengguna": "User",
    "Penggunaan": "Usage",
    "Penutupan Tahun Kewangan": "Financial Year-End Closing",
    "Penutupan kedua tidak dibenarkan.": "A second closing is not allowed.",
    "Penyedia": "Provider",
    "Per transaksi (setiap kutipan/bayaran/jurnal)": "Per transaction (every collection/payment/journal)",
    "Peranan": "Role",
    "Percubaan Log Masuk": "Login Attempts",
    "Permohonan Menunggu": "Pending Requests",
    "Peruntukan": "Allocations",
    "Peruntukan (RM)": "Allocation (RM)",
    "Peruntukan lwn Perbelanjaan Sebenar": "Allocation vs Actual Expenditure",
    "Petakan label tempatan masjid kepada COA piawai.": "Map the mosque's local labels to the standard COA.",
    'Pilih "Ya, Log Keluar" jika anda sudah selesai.': 'Choose "Yes, Log Out" if you are done.',
    "Pilih Bank": "Select Bank",
    "Pilih dana sedia ada untuk kemaskini:": "Select an existing fund to update:",
    "Pilihan Paparan Penyata": "Statement Display Options",
    "Poskod": "Postcode",
    "Pratonton": "Preview",
    "Pratonton Untung Rugi": "Profit & Loss Preview",
    "Profil Masjid": "Mosque Profile",
    "Proses Tertunggak": "Process Pending",
    "Provider AI Vision": "AI Vision Providers",
    "Provider:": "Provider:",
    "QR": "QR",
    "Ralat": "Error",
    "Ralat 7 Hari": "Errors 7 Days",
    "Ralat Terakhir": "Last Error",
    "Recno": "Recno",
    "Rekod kekal untuk rujukan transaksi.": "The record is kept for transaction reference.",
    "Reset & Edit Semula": "Reset & Edit Again",
    "Reset & Edit Semula?": "Reset & Edit Again?",
    "Reset Kata Laluan (kosongkan jika tidak ditukar)": "Reset Password (leave blank to keep)",
    "SEBELUM": "BEFORE",
    "SELEPAS": "AFTER",
    "SELESAI": "RESOLVED",
    "SNT terkumpul": "accumulated depreciation",
    "Sahkan & Rekod": "Confirm & Record",
    "Sahkan Kata Laluan Baharu": "Confirm New Password",
    "Sahkan Pelupusan": "Confirm Disposal",
    "Sahkan Rantai": "Verify Chain",
    "Sahkan SEMUA draf yang dipilih? Setiap draf akan direkodkan sebagai transaksi sebenar.": "Confirm ALL selected drafts? Each draft will be recorded as a real transaction.",
    "Sahkan Semua Dipilih": "Confirm All Selected",
    "Sahkan Tolak": "Confirm Rejection",
    "Sahkan draf ini? Transaksi & jurnal sebenar akan direkodkan.": "Confirm this draft? A real transaction & journal will be recorded.",
    "Saiz": "Size",
    "Saiz font": "Font size",
    "Saya faham Akaun Sementara masih berbaki dan": "I understand the Suspense Account still has a balance and",
    "Scopes": "Scopes",
    "Scopes (kebenaran)": "Scopes (permissions)",
    "Sebab Pelupusan": "Disposal Reason",
    "Sebab Penolakan": "Rejection Reason",
    "Sebab penolakan (pilihan)": "Rejection reason (optional)",
    "Sebenar (RM)": "Actual (RM)",
    "Secret (HMAC)": "Secret (HMAC)",
    "Secret HMAC (opsional)": "HMAC Secret (optional)",
    "Secret tidak disimpan dalam sistem (hash sahaja). Jika hilang, cipta klien baharu.": "The secret is not stored in the system (hash only). If lost, create a new client.",
    "Security Event": "Security Events",
    "Sedia untuk log keluar?": "Ready to log out?",
    "Sejarah Keputusan (30 terkini)": "Decision History (30 latest)",
    "Selepas dikunci, pengeditan memerlukan Reset & Edit Semula.": "Once locked, editing requires Reset & Edit Again.",
    "Selepas tutup, semua tempoh sehingga": "After closing, all periods up to",
    "Selesai": "Done",
    "Semak": "Review",
    "Semak Draf AI": "Review AI Draft",
    "Semak Padanan": "Check Matches",
    "Semasa:": "Current:",
    "Semua": "All",
    "Semua (termasuk selesai)": "All (including resolved)",
    "Semua akaun tabung 300-04xxx telah didaftarkan.": "All 300-04xxx fund accounts have been registered.",
    "Semua fail disulitkan dengan APP_KEY sebelum dimuat naik (.enc).": "All files are encrypted with the APP_KEY before upload (.enc).",
    "Semua tahap": "All levels",
    "Senarai Akaun Bank (Maksimum 3 Slot)": "Bank Account List (Maximum 3 Slots)",
    "Senarai Aset & Jadual Susut Nilai": "Asset List & Depreciation Schedule",
    "Senarai Dana / Tabung (COA 300-04xxx)": "Fund / Trust List (COA 300-04xxx)",
    "Senarai Pengguna": "User List",
    "Set": "Set",
    "Set No. Resit/Baucer": "Set Receipt/Voucher Numbers",
    "Setiap akaun Hasil/Belanja disifarkan; baki bersih dipindah ke": "Every Revenue/Expense account is zeroed; the net balance is transferred to",
    "Setup lengkap — sistem sedia digunakan.": "Setup complete — the system is ready to use.",
    "Sila semak transaksi dana atau benarkan defisit jika disengajakan.": "Please review the fund's transactions or allow the deficit if intentional.",
    "Simpan Konfigurasi": "Save Configuration",
    "Simpan Pemetaan": "Save Mapping",
    "Simpan Pilihan Paparan": "Save Display Options",
    "Simpan Provider": "Save Provider",
    "Simpan Tandatangan": "Save Signature",
    "Simpan Telegram": "Save Telegram",
    "Simpan ke Vault": "Save to Vault",
    "Sisi": "Side",
    "Sistem Pengurusan & Audit Kewangan Masjid": "Mosque Financial Management & Audit System",
    "Sistem Terkunci": "System Locked",
    "Sokong Vision": "Supports Vision",
    "Status Backup": "Backup Status",
    "Status Penghantaran": "Delivery Status",
    "Sumber": "Source",
    "Susunan": "Order",
    "Susut Nilai Aset": "Asset Depreciation",
    "Susut penuh": "Fully depreciated",
    "Susut/Bulan (RM)": "Depreciation/Month (RM)",
    "TIDAK AKTIF": "INACTIVE",
    "TUTUP TAHUN": "CLOSE YEAR",
    "Tahap": "Level",
    "Tahun Belanjawan": "Budget Year",
    "Tahun Kewangan": "Financial Year",
    "Tahun Semasa": "Current Year",
    "Tambah": "Add",
    "Tambah / Kemaskini Dana": "Add / Update Fund",
    "Tambah Bank": "Add Bank",
    "Tambah Bank Baru": "Add New Bank",
    "Tambah Baris": "Add Row",
    "Tambah Pemetaan Baru": "Add New Mapping",
    "Tambah Pengguna": "Add User",
    "Tambah Pengguna Baru": "Add New User",
    "Tambah Provider AI": "Add AI Provider",
    "Tambah Tandatangan": "Add Signature",
    "Tandatangan": "Signatures",
    "Tandatangan Penyata": "Statement Signatures",
    "Tapis": "Filter",
    "Tapisan": "Filters",
    "Target URL": "Target URL",
    "Teks Disclaimer": "Disclaimer Text",
    "Telefon": "Phone",
    "Telefon / Fax": "Phone / Fax",
    "Telegram harian.": "Telegram alert.",
    "Tempoh Simpanan (hari)": "Retention Period (days)",
    "Tempoh dikunci sehingga": "Periods locked until",
    "Terakhir Guna": "Last Used",
    "Tersimpan dalam vault:": "Stored in vault:",
    "Tetapan Dual-Write": "Dual-Write Settings",
    "Tetapan Kawalan Dalaman": "Internal Control Settings",
    "Tetapkan": "Set up",
    "Tetapkan akaun bank masjid (slot 1–3) dan petakan ke COA 250-050x0.": "Set up the mosque's bank accounts (slots 1–3) and map them to COA 250-050x0.",
    "Tetapkan turutan nombor resit, PV, PWR dan jurnal.": "Set the numbering sequences for receipts, PV, petty cash and journals.",
    "Tiada akaun bank didaftarkan.": "No bank accounts registered.",
    "Tiada akaun bank didaftarkan. Sila daftar bank dahulu di Setting Bank.": "No bank accounts registered. Please register a bank first in Bank Settings.",
    "Tiada aktiviti audit.": "No audit activity.",
    "Tiada aset sepadan.": "No matching assets.",
    "Tiada baris belum dipadan.": "No unmatched lines.",
    "Tiada dana didaftarkan.": "No funds registered.",
    "Tiada draf menunggu pengesahan.": "No drafts awaiting confirmation.",
    "Tiada fail dilampirkan.": "No file attached.",
    "Tiada klien API didaftarkan.": "No API clients registered.",
    "Tiada kutipan sepadan.": "No matching collections.",
    "Tiada lagi": "None yet",
    "Tiada langganan webhook.": "No webhook subscriptions.",
    "Tiada logo dimuat naik.": "No logo uploaded.",
    "Tiada notifikasi baharu.": "No new notifications.",
    "Tiada padanan ≥ 40% ditemui.": "No matches ≥ 40% found.",
    "Tiada panggilan API direkodkan.": "No API calls recorded.",
    "Tiada pembayaran sepadan.": "No matching payments.",
    "Tiada pemetaan kod.": "No code mappings.",
    "Tiada pengguna.": "No users.",
    "Tiada percubaan log masuk.": "No login attempts.",
    "Tiada permohonan menunggu kelulusan.": "No requests awaiting approval.",
    "Tiada peruntukan": "No allocation",
    "Tiada provider AI. Tambah di bawah.": "No AI providers. Add one below.",
    "Tiada ralat — sistem sihat.": "No errors — system healthy.",
    "Tiada rekod audit sepadan tapisan.": "No audit records match the filters.",
    "Tiada rekod ekstrakan AI untuk draf ini.": "No AI extraction record for this draft.",
    "Tiada rekod sync.": "No sync records.",
    "Tiada security event.": "No security events.",
    "Tiada sejarah.": "No history.",
    "Tiada tandatangan didaftarkan.": "No signatures registered.",
    "Tiada transaksi direkodkan": "No transactions are recorded",
    "Tiada transaksi.": "No transactions.",
    "Tiada voucher calon — cuba carian lain.": "No candidate vouchers — try another search.",
    "Tidak": "No",
    "Tidak digunakan": "Not used",
    "Tindakan ini mengunci semua tempoh sehingga": "This action locks all periods up to",
    "Token Bot": "Bot Token",
    "Tolak": "Reject",
    "Tolak Permohonan": "Reject Request",
    "Tolak draf ini? Tiada transaksi akan direkodkan.": "Reject this draft? No transaction will be recorded.",
    "Transaksi": "Transactions",
    "Transaksi Dana:": "Fund Transactions:",
    "Transaksi Hari Ini": "Transactions Today",
    "URL": "URL",
    "URL Webhook:": "Webhook URL:",
    "Ubah had di halaman": "Change the threshold on the",
    "Uji Sambungan": "Test Connection",
    "User-Agent": "User-Agent",
    "Voucher": "Voucher",
    "Voucher penutupan": "Closing voucher",
    "Wizard Setup Sistem": "System Setup Wizard",
    "Ya": "Yes",
    "admin/pengerusi di halaman": "by an admin/chairman on the",
    "akan DIBATALKAN dan kunci dibuka. Anda perlu simpan dan muktamadkan semula.": "will be CANCELLED and the lock released. You will need to save and finalise again.",
    "aset": "assets",
    "baki awal tahun": "the opening balances for year",
    "bayaran bendahari melebihi had memerlukan kelulusan admin/pengerusi sebelum direkodkan ke jurnal.": "treasurer payments above the threshold require admin/chairman approval before being recorded to the journal.",
    "belum selesai": "unresolved",
    "bendahari": "treasurer",
    "berbaki": "has a balance of",
    "cth: KUTIPAN JUMAAT": "e.g. FRIDAY COLLECTION",
    "cth: Sistem Portal MAIWP": "e.g. MAIWP Portal System",
    "cth: bukan resit masjid / pendua / tidak jelas": "e.g. not a mosque receipt / duplicate / unclear",
    "cth: elaun, sumbangan, bil api": "e.g. allowance, donation, electricity bill",
    "cth: gpt-4o / claude-opus-4-8": "e.g. gpt-4o / claude-opus-4-8",
    "cth: https://api.deepseek.com": "e.g. https://api.deepseek.com",
    "cth: malmutaqqin": "e.g. malmutaqqin",
    "dalam sistem ini turut dihantar ke borang SPPKMS lama": "in this system is also sent to the legacy SPPKMS form",
    "dan tidak boleh diundur dari halaman ini.": "and cannot be undone from this page.",
    "di SPPKMS lama (amaran Telegram dihantar).": "in the legacy SPPKMS (a Telegram alert is sent).",
    "di bawah untuk meneruskan juga (tidak digalakkan).": "below to proceed anyway (not recommended).",
    "di-SKIP (borang aset lama kompleks — hantar manual). Rekod yang dibatalkan di sini": "are SKIPPED (the legacy asset form is complex — submit manually). Records voided here",
    "dibina untuk ketepatan audit. Semua laporan dikira terus daripada jurnal.": "built for audit accuracy. All reports are computed directly from the journal.",
    "dijana secara automatik": "is generated automatically",
    "dipadam manual": "deleted manually",
    "diposkan pada tempoh maya": "is posted in the virtual period",
    "direkod dalam jejak audit hash-chain.": "are recorded in the hash-chain audit trail.",
    "direkodkan ke jurnal.": "being recorded to the journal.",
    "draf": "drafts",
    "dual-write SPPKMS?": "SPPKMS dual-write?",
    "event HIGH/CRITICAL": "HIGH/CRITICAL events",
    "item barisan backup berstatus GAGAL.": "backup queue item(s) with FAILED status.",
    "jadual hanya menyimpan rujukan": "tables only store references",
    "jambatan sementara semasa tempoh peralihan.": "a temporary bridge during the transition period.",
    "jika kadar tiada).": "if no rate is set).",
    "jurnal direkod selepas pengesahan bendahari sahaja.": "journals are recorded only after the treasurer's confirmation.",
    "klien": "client",
    "kos": "cost",
    "kotak draf": "draft inbox",
    "kutipan": "collections",
    "kutipan/pembayaran baharu": "new collection/payment",
    "langkah selesai": "steps completed",
    "laporan P&L bulanan/tahunan sejarah": "historical monthly/annual P&L reports",
    "log percubaan": "attempt log",
    "lwn": "vs",
    "manual": "manual",
    "masih berbaki": "still has a balance of",
    "matang": "matures",
    "melebihi had ini perlu kelulusan": "exceeding this threshold require approval",
    "mengesahkan untuk meneruskan": "confirm to proceed with",
    "menunggu": "pending",
    "menunggu pengesahan": "awaiting confirmation",
    "nilai buku": "book value",
    "openai (juga DeepSeek/Qwen)": "openai (also DeepSeek/Qwen)",
    "pada": "on",
    "papar senarai tandatangan di bahagian bawah penyata": "show the signature list at the bottom of statements",
    "papar teks penafian di bahagian bawah penyata": "show a disclaimer text at the bottom of statements",
    "pelulus (checker) adalah orang berbeza bagi amaun besar. Semua keputusan kelulusan": "checker are different people for large amounts. All approval decisions",
    "pembayaran": "payments",
    "penerima:": "payee:",
    "penutupan tahun.": "the year-end closing.",
    "perlu": "must be",
    "rekod dijumpai": "records found",
    "sebelum": "page before",
    "sebelum menutup tahun — atau tandakan kotak pengesahan": "before closing the year — or tick the confirmation box",
    "sebulan (atau": "per month (or",
    "sedang dibina": "is under construction",
    "sehingga bendahari menyemak & mengesahkan setiap draf.": "until the treasurer reviews & confirms each draft.",
    "semuanya disulitkan dalam vault;": "all encrypted in the vault;",
    "sila semak setiap medan dengan teliti sebelum mengesahkan.": "please review every field carefully before confirming.",
    "sistem": "system",
    "tabung ini tidak dibenarkan defisit.": "this fund is not allowed to be in deficit.",
    "tanpanya fail tidak boleh dipulihkan.": "without it the files cannot be restored.",
    "telah dimuktamadkan.": "have been finalised.",
    "telah pun ditutup (voucher": "has already been closed (voucher",
    "terakhir:": "last:",
    "tetapan backup": "backup settings",
    "thn": "yrs",
    "tiada transaksi/pembatalan baharu dibenarkan.": "no new transactions/reversals are allowed.",
    "tidak berubah": "do not change",
    "tidak disimpan plaintext": "not stored in plaintext",
    "voucher jurnal dicipta": "journal vouchers created",
    "wujud).": "exists).",
    "— semua —": "— all —",
    "••••••••  (tersimpan)": "••••••••  (saved)",
}

path = os.path.join(BASE, "lang", "en.json")
en = json.load(io.open(path, encoding="utf-8"), object_pairs_hook=OrderedDict)
asal = len(en)

# semak konflik dengan kunci sedia ada
konflik = [k for k in NEW if k in en]
if konflik:
    print("KONFLIK (sudah wujud, dilangkau):", len(konflik))
    for k in konflik:
        NEW.pop(k)

for k, v in NEW.items():
    en[k] = v

with io.open(path, "w", encoding="utf-8", newline="\n") as f:
    json.dump(en, f, ensure_ascii=False, indent=4)
    f.write("\n")

# sahkan JSON sah + tiada pendua
semak = json.load(io.open(path, encoding="utf-8"))
print("Kunci asal:", asal, "| Tambah:", len(NEW), "| Jumlah kini:", len(semak))

# pastikan semua kunci _missing.json kini ada
missing = json.load(io.open(os.path.join(BASE, "_missing.json"), encoding="utf-8"))
belum = [k for k in missing if k not in semak]
print("Masih belum ada:", len(belum))
for k in belum:
    print(repr(k))
